# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lab/lines-two-level

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lab/lines-two-level

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lab/lines-two-level/CMakeFiles /home/lab/lines-two-level/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lab/lines-two-level/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named line

# Build rule for target.
line: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 line
.PHONY : line

# fast build rule for target.
line/fast:
	$(MAKE) -f CMakeFiles/line.dir/build.make CMakeFiles/line.dir/build
.PHONY : line/fast

line.o: line.cpp.o

.PHONY : line.o

# target to build an object file
line.cpp.o:
	$(MAKE) -f CMakeFiles/line.dir/build.make CMakeFiles/line.dir/line.cpp.o
.PHONY : line.cpp.o

line.i: line.cpp.i

.PHONY : line.i

# target to preprocess a source file
line.cpp.i:
	$(MAKE) -f CMakeFiles/line.dir/build.make CMakeFiles/line.dir/line.cpp.i
.PHONY : line.cpp.i

line.s: line.cpp.s

.PHONY : line.s

# target to generate assembly for a file
line.cpp.s:
	$(MAKE) -f CMakeFiles/line.dir/build.make CMakeFiles/line.dir/line.cpp.s
.PHONY : line.cpp.s

line_projection_factor.o: line_projection_factor.cpp.o

.PHONY : line_projection_factor.o

# target to build an object file
line_projection_factor.cpp.o:
	$(MAKE) -f CMakeFiles/line.dir/build.make CMakeFiles/line.dir/line_projection_factor.cpp.o
.PHONY : line_projection_factor.cpp.o

line_projection_factor.i: line_projection_factor.cpp.i

.PHONY : line_projection_factor.i

# target to preprocess a source file
line_projection_factor.cpp.i:
	$(MAKE) -f CMakeFiles/line.dir/build.make CMakeFiles/line.dir/line_projection_factor.cpp.i
.PHONY : line_projection_factor.cpp.i

line_projection_factor.s: line_projection_factor.cpp.s

.PHONY : line_projection_factor.s

# target to generate assembly for a file
line_projection_factor.cpp.s:
	$(MAKE) -f CMakeFiles/line.dir/build.make CMakeFiles/line.dir/line_projection_factor.cpp.s
.PHONY : line_projection_factor.cpp.s

pose_local_parameterization.o: pose_local_parameterization.cpp.o

.PHONY : pose_local_parameterization.o

# target to build an object file
pose_local_parameterization.cpp.o:
	$(MAKE) -f CMakeFiles/line.dir/build.make CMakeFiles/line.dir/pose_local_parameterization.cpp.o
.PHONY : pose_local_parameterization.cpp.o

pose_local_parameterization.i: pose_local_parameterization.cpp.i

.PHONY : pose_local_parameterization.i

# target to preprocess a source file
pose_local_parameterization.cpp.i:
	$(MAKE) -f CMakeFiles/line.dir/build.make CMakeFiles/line.dir/pose_local_parameterization.cpp.i
.PHONY : pose_local_parameterization.cpp.i

pose_local_parameterization.s: pose_local_parameterization.cpp.s

.PHONY : pose_local_parameterization.s

# target to generate assembly for a file
pose_local_parameterization.cpp.s:
	$(MAKE) -f CMakeFiles/line.dir/build.make CMakeFiles/line.dir/pose_local_parameterization.cpp.s
.PHONY : pose_local_parameterization.cpp.s

utility.o: utility.cpp.o

.PHONY : utility.o

# target to build an object file
utility.cpp.o:
	$(MAKE) -f CMakeFiles/line.dir/build.make CMakeFiles/line.dir/utility.cpp.o
.PHONY : utility.cpp.o

utility.i: utility.cpp.i

.PHONY : utility.i

# target to preprocess a source file
utility.cpp.i:
	$(MAKE) -f CMakeFiles/line.dir/build.make CMakeFiles/line.dir/utility.cpp.i
.PHONY : utility.cpp.i

utility.s: utility.cpp.s

.PHONY : utility.s

# target to generate assembly for a file
utility.cpp.s:
	$(MAKE) -f CMakeFiles/line.dir/build.make CMakeFiles/line.dir/utility.cpp.s
.PHONY : utility.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... line"
	@echo "... edit_cache"
	@echo "... line.o"
	@echo "... line.i"
	@echo "... line.s"
	@echo "... line_projection_factor.o"
	@echo "... line_projection_factor.i"
	@echo "... line_projection_factor.s"
	@echo "... pose_local_parameterization.o"
	@echo "... pose_local_parameterization.i"
	@echo "... pose_local_parameterization.s"
	@echo "... utility.o"
	@echo "... utility.i"
	@echo "... utility.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

